spring:
  application:
    name: rebuild-action
    
  datasource:
    url: jdbc:mysql://${DATABASE_HOST}:3306/${DATABASE}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
